name: Deploy to Beamup (beamup-config)

on:
  push:
    branches:
      - beamup-config
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy
        uses: Stremio/beamup-deploy-action@v1.0.1
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          beamup_host: ${{ secrets.BEAMUP_HOST }}
          username_github: fopina-beamup
          project_name: stremio-fpptv
